export const LAUNCHES_FETCHED = 'LAUNCHES_FETCHED';
export const LAUNCHES_FETCH_ERROR = 'LAUNCHES_FETCH_ERROR';
export const PAGINATE = 'PAGINATE';
export const MODAL_ACTION = 'MODAL_ACTION';
export const LAUNCHES_DETAILS_FETCHED = 'LAUNCHES_DETAILS_FETCHED';
export const LAUNCH_STATUS_FILTER = 'LAUNCH_STATUS_FILTER';
